#!/bin/bash
#
# Copy the required files into data/web that live elsewhere in our source tree.
#  We use rsync to be able to avoid copying .git subtrees, but it also should
#  generally increase performance.
#
# Do an "rm -rf data/web" if you want to clean up our byproducts.  We can't
#  pass "--delete --delete-excluded" on the rsync command line right now since
#  we need to do a few copying passes.

# --delete --delete-excluded
CPCMD="rsync -avL --exclude-from .acfx-exclude"

## Copy over UI used by the content part of the addon.
mkdir -p data/web
mkdir -p data/web/deps

mkdir -p data/web/deps/rdctests

## Source Tree Location => jetpack 'data' location

# clients/deps        => web/deps
# clients/mobileui    => web/mobileui
# clients/devui       => web/devui
# clients/logui       => web/logui
$CPCMD ../deps ../mobileui ../devui ../logui data/web

# common/lib/rdcommon => web/deps/rdcommon
$CPCMD ../../common/lib/rdcommon data/web/deps

# common/test         => web/deps/rdctests
$CPCMD ../../common/test/*.js data/web/deps/rdctests

# clients/addon/lib/nacl-native-libs => data/nacl-native-libs
$CPCMD lib/nacl-native-libs data

# To run tests, you may want to also provide the following args.  This is
# possibly moot, but I am deleting the files that contained this info, so let's
# keep it around somewhere for now...
#  --package-path ../../common \
#  --package-path ../../common/test \
#  --extra-packages "addon-kit,rdcommon,rdctests"

## Run jetpack
cfx "$@"

