#!/bin/sh

# also adds the client test directories as a package; not somethign we want in
#  anything but testing situations

EXTRA=

cfx $EXTRA \
 --package-path ../../common \
 --package-path ../../common/test \
 --extra-packages "addon-kit,rdcommon,rdctests" \
 "$@"
